# Generated by Django 5.2.11 on 2026-03-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdoctoraccess',
            name='consent_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdoctoraccess',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
