# Generated by Django 5.2.11 on 2026-04-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_patientdoctoraccess_consent_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploadrequest',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdoctoraccess',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
