# Generated by Django 5.2.11 on 2026-02-24 04:35

import django.db.models.deletion
import django_mongodb_backend.fields
import medfiles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDocChunk',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('batch_hash', models.CharField(db_index=True, max_length=64)),
                ('chunk_id', models.CharField(db_index=True, default=0, max_length=120)),
                ('chunk_index', models.IntegerField()),
                ('text', models.TextField()),
                ('source_file_ids', models.JSONField(default=list)),
                ('source_file_names', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('embedding', models.JSONField(default=list)),
                ('embedding_model', models.CharField(default='BAAI/bge-small-en-v1.5', max_length=80)),
                ('embedding_norm', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_chunks_as_doctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_chunks_as_patient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['patient', 'doctor', 'batch_hash'], name='medfiles_pa_patient_d00746_idx')],
                'constraints': [models.UniqueConstraint(fields=('patient', 'doctor', 'chunk_id'), name='uniq_patient_doctor_chunkid')],
            },
        ),
        migrations.CreateModel(
            name='PatientFile',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', max_length=120)),
                ('file_type', models.CharField(default='unknown', max_length=20)),
                ('file', models.FileField(upload_to=medfiles.models.upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('chunk_id', models.CharField(db_index=True, max_length=120)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_files', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['patient', 'doctor', 'uploaded_at'], name='medfiles_pa_patient_3e64fd_idx')],
            },
        ),
    ]
