# Generated by Django 5.2.11 on 2026-02-24 05:06

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdocchunk',
            name='source_file_ids',
            field=django_mongodb_backend.fields.ArrayField(base_field=models.CharField(max_length=64), default=list),
        ),
        migrations.AlterField(
            model_name='patientdocchunk',
            name='source_file_names',
            field=django_mongodb_backend.fields.ArrayField(base_field=models.CharField(max_length=255), default=list),
        ),
    ]
