# Generated by Django 5.2.11 on 2026-03-23 18:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medfiles', '0002_alter_patientdocchunk_source_file_ids_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientfile',
            name='chunk_id',
        ),
        migrations.AddField(
            model_name='patientfile',
            name='authorized_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientfile',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='patientfile',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='patientfile',
            name='disposed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientfile',
            name='extracted_payload',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='patientfile',
            name='extracted_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='patientfile',
            name='is_disposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientfile',
            name='last_error',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='patientfile',
            name='processing_status',
            field=models.CharField(default='uploaded', max_length=20),
        ),
        migrations.AddField(
            model_name='patientfile',
            name='processing_steps',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='patientfile',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='patientdocchunk',
            name='chunk_id',
            field=models.CharField(db_index=True, default='', max_length=120),
        ),
        migrations.AddIndex(
            model_name='patientfile',
            index=models.Index(fields=['patient', 'doctor', 'is_disposed'], name='medfiles_pa_patient_88de59_idx'),
        ),
    ]
