# Generated by Django 5.2.11 on 2026-04-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medfiles', '0003_remove_patientfile_chunk_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientfile',
            name='extension',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='patientfile',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patientfile',
            name='last_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientfile',
            name='sha256',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='patientfile',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='patientfile',
            name='uploaded_by_role',
            field=models.CharField(default='patient', max_length=20),
        ),
    ]
