# Generated by Django 5.2.11 on 2026-04-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medfiles', '0004_patientfile_extension_patientfile_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdocchunk',
            name='source_file_id',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='patientdocchunk',
            name='source_file_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
